import type { Metadata } from "next";
import { Anton, Poppins, Bebas_Neue } from "next/font/google";

import "./globals.css";
import Header from "@/components/share/Header";
import Footer from "@/components/share/Footer";
const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: ["400"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"], // Bebas Neue (Google Fonts) only has 400
  variable: "--font-bebas",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anton.variable} ${poppins.variable} ${bebasNeue.variable} antialiased text-[#FFFFFF] `}
        style={{ fontFamily: "Poppins" }}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
